name: Release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  ios:
    name: iOS

    runs-on: macos-12

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: ios-cmake-v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/ios.toolchain.cmake \
            -D ENABLE_BITCODE=0 \
            -D PLATFORM=OS64 \
            -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY='' \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            -j $(sysctl -n hw.physicalcpu) \
            # EOL

      - name: Pack
        run: |
          cd build
          cpack -C RelWithDebInfo

      - name: Upload
        run: |
          cd build
          cp fallout-ce.ipa fallout-ce-ios.ipa
          gh release upload ${{ github.event.release.tag_name }} fallout-ce-ios.ipa
          rm fallout-ce-ios.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: macOS

    runs-on: macos-13

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Import code signing certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_PASSWORD }}

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: macos-cmake-v3

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="${{ secrets.APPLE_DEVELOPER_CERTIFICATE_IDENTITY }}" \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS="NO" \
            -D CMAKE_XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS="--options=runtime --timestamp" \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            -j $(sysctl -n hw.physicalcpu) \
            # EOL

      - name: Pack
        run: |
          cd build
          cpack -C RelWithDebInfo

      - name: Notarize
        run: |
          brew install mitchellh/gon/gon
          cat << EOF > config.json
          {
            "notarize": {
              "path": "build/Fallout Community Edition.dmg",
              "bundle_id": "$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "build/RelWithDebInfo/Fallout Community Edition.app/Contents/Info.plist")",
              "staple": true
            }
          }
          EOF
          gon config.json
          rm config.json
        env:
          AC_USERNAME: ${{ secrets.APPLE_DEVELOPER_AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.APPLE_DEVELOPER_AC_PASSWORD }}

      - name: Upload
        run: |
          cd build
          cp "Fallout Community Edition.dmg" fallout-ce-macos.dmg
          gh release upload ${{ github.event.release.tag_name }} fallout-ce-macos.dmg
          rm fallout-ce-macos.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

